### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [cynrick/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Once you figured that step out, add a link to the corresponding commit in the comments below :)

**Comment by trisalar** [comment]
Hey Marco,

I added the meta tag for mobile devices and it seems to work/look a lot better now like you suggested. =)

https://github.com/CynrickChiu/splurty/blob/master/app/views/layouts/application.html.erb

**Comment by MarcoMorawec** [comment]
@CynrickChiu  :+1: 

Looks like you got it done right [in this commit](https://github.com/CynrickChiu/splurty/commit/d41d3c8af802abca82caca12de95ca106fadd1ad)

Make sure you close the issue, now that you solved it :)
